repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.1'
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: '21.12b0'
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        args:
          - --profile=black

  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
        args:
          - --max-line-length=88

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.1"
    hooks:
      - id: bandit
        exclude: tests/

  - repo: https://github.com/codespell-project/codespell
    rev: 'v2.1.0'
    hooks:
      - id: codespell

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: 'v1.2.2'
    hooks:
      - id: python-safety-dependencies-check