---
version: '3.7'
services:

  airsensor:
    restart: unless-stopped
    hostname: airsensor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5110:5110
    command: uvicorn air_sensor.asgi:app --host 0.0.0.0 --port 5110
    env_file: .env
    environment:
      PYTHONPATH: /code/


  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml